apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: http-endpoint
  name: http-endpoint
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: http-endpoint
  template:
    metadata:
      labels:
        app: http-endpoint
    spec:
      containers:
      - image: vkhazin/courseware-nodejs-container
        imagePullPolicy: Always
        name: http-endpoint
        env:
        - name: PORT
          value: "3000"